GET http://localhost:3000/matchenatinderze?channelId=799677088609075212&startDate=2025-04-13T00:00:00Z&endDate=2025-04-14T00:00:00Z

### wrong request

GET http://localhost:3000/matchenatinderze

###

POST http://localhost:8000/ruchniecie
Content-Type: application/json

{
    "channelId": "799677088609075212",
    "threadId": "1234567890",
    "messages": [
        {
            "username": "user1",
            "message": "Co się działo 17 kwietnia 2025 między 19:00 a 23:00?",
            "images": []
        }
    ]
}

            # "message": "Co się działo od 5 do 7 kwietnia 2025?",
### 

GET http://localhost:8000/cache

### 

DELETE http://localhost:8000/cache