### Variables
@baseUrl = http://localhost:8000

### Welcome endpoint
GET {{baseUrl}}/
Accept: application/json

### Ruchniecie
POST {{baseUrl}}/ruchniecie
Content-Type: application/json

{
    "messages": [
        {
            "username": "John",
            "message": "Hello, how are you?"
        },
        {
            "username": "Jane",
            "message": "I'm good, thank you!"
        }
    ]
}
