### Variables
@baseUrl = http://localhost:8000

### Welcome endpoint
GET {{baseUrl}}/
Accept: application/json

### Ruchniecie
POST {{baseUrl}}/ruchniecie
Content-Type: application/json

{
    "text": "This is some example text"
}
