### Variables
@baseUrl = http://localhost:8000

### Welcome endpoint
GET {{baseUrl}}/
Accept: application/json

### Ruchniecie
POST {{baseUrl}}/ruchniecie
Content-Type: application/json

{
    "messages": [
        {
            "username": "Domin",
            "message": "Summarize messages from channel 1234 between 2024-01-01 and 2024-01-02"
        }
    ]
}
